#ifndef GEARS_FUNC_ORDER_DEFINITION_H
#define GEARS_FUNC_ORDER_DEFINITION_H

#include <Internal/FuncOrder.h>

FUNC_ORDER(Initialize)
FUNC_ORDER(Update)
FUNC_ORDER(BeginDraw)
FUNC_ORDER(Draw)
FUNC_ORDER(DebugDraw)
FUNC_ORDER(EndDraw)
FUNC_ORDER(Finalize)

#endif // !GEARS_FUNC_ORDER_DEFINITION_H