#ifndef GEARS_FUNC_DEFINITION_H
#define GEARS_FUNC_DEFINITION_H

#include <Internal/HasFunctionObject.h>

HAS_FUNC_OBJECT(Initialize);
HAS_FUNC_OBJECT(BeginDraw);
HAS_FUNC_OBJECT(DebugDraw);
HAS_FUNC_OBJECT(EndDraw);
HAS_FUNC_OBJECT(Finalize);

HAS_FUNC_OBJECT(Start);
HAS_FUNC_OBJECT(Update);
HAS_FUNC_OBJECT(LateUpdate);
HAS_FUNC_OBJECT(Draw);

#endif // !GEARS_FUNC_DEFINITION_H
