#pragma once

namespace Glib
{
    /**
     * @brief キーボード列挙型
    */
    enum class KeyCode : unsigned
    {
        None = 0,                   // キーなし
        Escape = 0x01,              // ESCキー
        D1 = 0x02,                  // 1キー
        D2 = 0x03,                  // 2キー
        D3 = 0x04,                  // 3キー
        D4 = 0x05,                  // 4キー
        D5 = 0x06,                  // 5キー
        D6 = 0x07,                  // 6キー
        D7 = 0x08,                  // 7キー
        D8 = 0x09,                  // 8キー
        D9 = 0x0A,                  // 9キー
        D0 = 0x0B,                  // 0キー
        Minus = 0x0C,               // -キー
        Equals = 0x0D,              // =キー
        Backspace = 0x0E,           // Backspaceキー
        Tab = 0x0F,                 // Tabキー
        Q = 0x10,                   // Qキー
        W = 0x11,                   // Wキー
        E = 0x12,                   // Eキー
        R = 0x13,                   // Rキー
        T = 0x14,                   // Tキー
        Y = 0x15,                   // Yキー
        U = 0x16,                   // Uキー
        I = 0x17,                   // Iキー
        O = 0x18,                   // Oキー
        P = 0x19,                   // Pキー
        LeftBracket = 0x1A,         // [キー
        RightBracket = 0x1B,        // ]キー
        Enter = 0x1C,               // Enterキー
        LeftControl = 0x1D,         // 左Ctrlキー
        A = 0x1E,                   // Aキー
        S = 0x1F,                   // Sキー
        D = 0x20,                   // Dキー
        F = 0x21,                   // Fキー
        G = 0x22,                   // Gキー
        H = 0x23,                   // Hキー
        J = 0x24,                   // Jキー
        K = 0x25,                   // Kキー
        L = 0x26,                   // Lキー
        Semicolon = 0x27,           // ;キー
        Apostrophe = 0x28,          // 'キー
        Grave = 0x29,               // `キー
        LeftShift = 0x2A,           // 左Shiftキー
        Backslash = 0x2B,           // \キー
        Z = 0x2C,                   // Zキー
        X = 0x2D,                   // Xキー
        C = 0x2E,                   // Cキー
        V = 0x2F,                   // Vキー
        B = 0x30,                   // Bキー
        N = 0x31,                   // Nキー
        M = 0x32,                   // Mキー
        Comma = 0x33,               // ,キー
        Period = 0x34,              // .キー
        Slash = 0x35,               // /キー
        RightShift = 0x36,          // 右Shiftキー
        Multiply = 0x37,            // *キー
        LeftAlt = 0x38,             // 左Altキー
        Space = 0x39,               // スペースキー
        CapsLock = 0x3A,            // Caps Lockキー
        F1 = 0x3B,                  // F1キー
        F2 = 0x3C,                  // F2キー
        F3 = 0x3D,                  // F3キー
        F4 = 0x3E,                  // F4キー
        F5 = 0x3F,                  // F5キー
        F6 = 0x40,                  // F6キー
        F7 = 0x41,                  // F7キー
        F8 = 0x42,                  // F8キー
        F9 = 0x43,                  // F9キー
        F10 = 0x44,                 // F10キー
        NumLock = 0x45,             // Num Lockキー
        ScrollLock = 0x46,          // Scroll Lockキー
        Numpad7 = 0x47,             // NumPad 7キー
        Numpad8 = 0x48,             // NumPad 8キー
        Numpad9 = 0x49,             // NumPad 9キー
        Subtract = 0x4A,            // - (NumPad)キー
        Numpad4 = 0x4B,             // NumPad 4キー
        Numpad5 = 0x4C,             // NumPad 5キー
        Numpad6 = 0x4D,             // NumPad 6キー
        Add = 0x4E,                 // + (NumPad)キー
        Numpad1 = 0x4F,             // NumPad 1キー
        Numpad2 = 0x50,             // NumPad 2キー
        Numpad3 = 0x51,             // NumPad 3キー
        Numpad0 = 0x52,             // NumPad 0キー
        Decimal = 0x53,             // . (NumPad)キー
        OEM_102 = 0x56,             // OEM 102キー
        F11 = 0x57,                 // F11キー
        F12 = 0x58,                 // F12キー
        F13 = 0x64,                 // F13キー
        F14 = 0x65,                 // F14キー
        F15 = 0x66,                 // F15キー
        Kana = 0x70,                // 日本語キーボードの「かな」キー
        Abnt_C1 = 0x73,             // Brazilian (ABNT_C1)キー
        Convert = 0x79,             // 変換キー
        NoConvert = 0x7B,           // 無変換キー
        Yen = 0x7D,                 // 日本語キーボードの円記号キー
        Abnt_C2 = 0x7E,             // Brazilian (ABNT_C2)キー
        NumpadEquals = 0x8D,        // NumPad =キー
        PrevTrack = 0x90,           // Previous Trackキー
        AT = 0x91,                  // ATキー
        Colon = 0x92,               // :キー
        Underline = 0x93,           // _キー
        Kanji = 0x94,               // 日本語キーボードの漢字キー
        Stop = 0x95,                // Stopキー
        AX = 0x96,                  // AXキー
        Unlabeled = 0x97,           // Unlabeledキー
        NextTrack = 0x99,           // Next Trackキー
        NumpadEnter = 0x9C,         // NumPad Enterキー
        RightControl = 0x9D,        // 右Ctrlキー
        Mute = 0xA0,                // ミュートキー
        Calculator = 0xA1,          // Calculatorキー
        PlayPause = 0xA2,           // Play / Pauseキー
        MediaStop = 0xA4,           // Media Stopキー
        VolumeDown = 0xAE,          // 音量ダウンキー
        VolumeUp = 0xB0,            // 音量アップキー
        WebHome = 0xB2,             // Web Homeキー
        NumpadComma = 0xB3,         // NumPad ,キー
        Divide = 0xB5,              // / (NumPad)キー
        SysRq = 0xB7,               // Print Screen / SysRqキー
        RightAlt = 0xB8,            // 右Altキー
        Pause = 0xC5,               // Pauseキー
        Home = 0xC7,                // Homeキー
        Up = 0xC8,                  // 上矢印キー
        PageUp = 0xC9,              // Page Upキー
        Left = 0xCB,                // 左矢印キー
        Right = 0xCD,               // 右矢印キー
        End = 0xCF,                 // Endキー
        Down = 0xD0,                // 下矢印キー
        PageDown = 0xD1,            // Page Downキー
        Insert = 0xD2,              // Insertキー
        Delete = 0xD3,              // Deleteキー
        LeftWindows = 0xDB,         // 左Windowsキー
        RightWindows = 0xDC,        // 右Windowsキー
        Apps = 0xDD,                // アプリケーションキー
        Power = 0xDE,               // 電源キー
        Sleep = 0xDF,               // スリープキー
        Wake = 0xE3,                // Wakeキー
        WebSearch = 0xE5,           // Web Searchキー
        WebFavorites = 0xE6,        // Web Favoritesキー
        WebRefresh = 0xE7,          // Web Refreshキー
        WebStop = 0xE8,             // Web Stopキー
        WebForward = 0xE9,          // Web Forwardキー
        WebBack = 0xEA,             // Web Backキー
        MyComputer = 0xEB,          // My Computerキー
        Mail = 0xEC,                // Mailキー
        MediaSelect = 0xED          // Media Selectキー
    };
}
