#pragma once

namespace Glib
{
    /**
     * @brief キーボード列挙型
    */
    enum class KeyCode : unsigned
    {
        None = 0x00,                // キーなし
        LButton = 0x01,             // マウス左ボタン
        RButton = 0x02,             // マウス右ボタン
        Cancel = 0x03,              // 制御中断
        MButton = 0x04,             // マウス中央ボタン
        XButton1 = 0x05,            // マウスX1ボタン
        XButton2 = 0x06,            // マウスX2ボタン
        Back = 0x08,                // Backspaceキー
        Tab = 0x09,                 // Tabキー
        Clear = 0x0C,               // Clearキー
        Enter = 0x0D,               // Enterキー
        Shift = 0x10,               // Shiftキー
        Control = 0x11,             // Ctrlキー
        Alt = 0x12,                 // Altキー
        Pause = 0x13,               // Pauseキー
        CapsLock = 0x14,            // Caps Lockキー
        Kana = 0x15,                // IME かなモード
        Hanguel = 0x15,             // IME ハングルモード (旧バージョン)
        Hangul = 0x15,              // IME ハングルモード
        Junja = 0x17,               // IME Junja モード
        Final = 0x18,               // IME Final モード
        Hanja = 0x19,               // IME Hanja モード
        Kanji = 0x19,               // IME Kanji モード
        Escape = 0x1B,              // Escキー
        Convert = 0x1C,             // IME 変換
        NonConvert = 0x1D,          // IME 無変換
        Accept = 0x1E,              // IME 変換
        ModeChange = 0x1F,          // IME モード変更リクエスト
        Space = 0x20,               // スペースキー
        PageUp = 0x21,              // Page Upキー
        PageDown = 0x22,            // Page Downキー
        End = 0x23,                 // Endキー
        Home = 0x24,                // Homeキー
        Left = 0x25,                // 左矢印キー
        Up = 0x26,                  // 上矢印キー
        Right = 0x27,               // 右矢印キー
        Down = 0x28,                // 下矢印キー
        Select = 0x29,              // Selectキー
        Print = 0x2A,               // Printキー
        Execute = 0x2B,             // Executeキー
        Snapshot = 0x2C,            // Print Screenキー
        Insert = 0x2D,              // Insertキー
        Delete = 0x2E,              // Deleteキー
        Help = 0x2F,                // Helpキー
        D0 = 0x30,                  // 0キー
        D1 = 0x31,                  // 1キー
        D2 = 0x32,                  // 2キー
        D3 = 0x33,                  // 3キー
        D4 = 0x34,                  // 4キー
        D5 = 0x35,                  // 5キー
        D6 = 0x36,                  // 6キー
        D7 = 0x37,                  // 7キー
        D8 = 0x38,                  // 8キー
        D9 = 0x39,                  // 9キー
        A = 0x41,                   // Aキー
        B = 0x42,                   // Bキー
        C = 0x43,                   // Cキー
        D = 0x44,                   // Dキー
        E = 0x45,                   // Eキー
        F = 0x46,                   // Fキー
        G = 0x47,                   // Gキー
        H = 0x48,                   // Hキー
        I = 0x49,                   // Iキー
        J = 0x4A,                   // Jキー
        K = 0x4B,                   // Kキー
        L = 0x4C,                   // Lキー
        M = 0x4D,                   // Mキー
        N = 0x4E,                   // Nキー
        O = 0x4F,                   // Oキー
        P = 0x50,                   // Pキー
        Q = 0x51,                   // Qキー
        R = 0x52,                   // Rキー
        S = 0x53,                   // Sキー
        T = 0x54,                   // Tキー
        U = 0x55,                   // Uキー
        V = 0x56,                   // Vキー
        W = 0x57,                   // Wキー
        X = 0x58,                   // Xキー
        Y = 0x59,                   // Yキー
        Z = 0x5A,                   // Zキー
        LWin = 0x5B,                // 左Windowsキー
        RWin = 0x5C,                // 右Windowsキー
        Apps = 0x5D,                // アプリケーションキー
        Sleep = 0x5F,               // スリープキー
        Numpad0 = 0x60,             // NumPad 0キー
        Numpad1 = 0x61,             // NumPad 1キー
        Numpad2 = 0x62,             // NumPad 2キー
        Numpad3 = 0x63,             // NumPad 3キー
        Numpad4 = 0x64,             // NumPad 4キー
        Numpad5 = 0x65,             // NumPad 5キー
        Numpad6 = 0x66,             // NumPad 6キー
        Numpad7 = 0x67,             // NumPad 7キー
        Numpad8 = 0x68,             // NumPad 8キー
        Numpad9 = 0x69,             // NumPad 9キー
        Multiply = 0x6A,            // * (NumPad)キー
        Add = 0x6B,                 // + (NumPad)キー
        Separator = 0x6C,           // セパレータキー
        Subtract = 0x6D,            // - (NumPad)キー
        Decimal = 0x6E,             // . (NumPad)キー
        Divide = 0x6F,              // / (NumPad)キー
        F1 = 0x70,                  // F1キー
        F2 = 0x71,                  // F2キー
        F3 = 0x72,                  // F3キー
        F4 = 0x73,                  // F4キー
        F5 = 0x74,                  // F5キー
        F6 = 0x75,                  // F6キー
        F7 = 0x76,                  // F7キー
        F8 = 0x77,                  // F8キー
        F9 = 0x78,                  // F9キー
        F10 = 0x79,                 // F10キー
        F11 = 0x7A,                 // F11キー
        F12 = 0x7B,                 // F12キー
        F13 = 0x7C,                 // F13キー
        F14 = 0x7D,                 // F14キー
        F15 = 0x7E,                 // F15キー
        F16 = 0x7F,                 // F16キー
        F17 = 0x80,                 // F17キー
        F18 = 0x81,                 // F18キー
        F19 = 0x82,                 // F19キー
        F20 = 0x83,                 // F20キー
        F21 = 0x84,                 // F21キー
        F22 = 0x85,                 // F22キー
        F23 = 0x86,                 // F23キー
        F24 = 0x87,                 // F24キー
        NumLock = 0x90,             // Num Lockキー
        ScrollLock = 0x91,          // Scroll Lockキー
        LShift = 0xA0,              // 左Shiftキー
        RShift = 0xA1,              // 右Shiftキー
        LControl = 0xA2,            // 左Ctrlキー
        RControl = 0xA3,            // 右Ctrlキー
        LAlt = 0xA4,                // 左Altキー
        RAlt = 0xA5,                // 右Altキー
        BrowserBack = 0xA6,         // ブラウザ戻るキー
        BrowserForward = 0xA7,      // ブラウザ進むキー
        BrowserRefresh = 0xA8,      // ブラウザ更新キー
        BrowserStop = 0xA9,         // ブラウザ停止キー
        BrowserSearch = 0xAA,       // ブラウザ検索キー
        BrowserFavorites = 0xAB,    // ブラウザお気に入りキー
        BrowserHome = 0xAC,         // ブラウザホームキー
        VolumeMute = 0xAD,          // 音量ミュートキー
        VolumeDown = 0xAE,          // 音量ダウンキー
        VolumeUp = 0xAF,            // 音量アップキー
        MediaNextTrack = 0xB0,      // 次のメディアトラックキー
        MediaPrevTrack = 0xB1,      // 前のメディアトラックキー
        MediaStop = 0xB2,           // メディア停止キー
        MediaPlayPause = 0xB3,      // メディア再生/一時停止キー
        LaunchMail = 0xB4,          // メール起動キー
        LaunchMediaSelect = 0xB5,   // メディア選択キー
        LaunchApp1 = 0xB6,          // アプリケーション1起動キー
        LaunchApp2 = 0xB7,          // アプリケーション2起動キー
        OEM_1 = 0xBA,               // 標準キーボード上の ';:' キー
        OEM_Plus = 0xBB,            // 標準キーボード上の '=' キー
        OEM_Comma = 0xBC,           // 標準キーボード上の ',' キー
        OEM_Minus = 0xBD,           // 標準キーボード上の '-' キー
        OEM_Period = 0xBE,          // 標準キーボード上の '.' キー
        OEM_2 = 0xBF,               // 標準キーボード上の '/?' キー
        OEM_3 = 0xC0,               // 標準キーボード上の '`~' キー
        OEM_4 = 0xDB,               // 標準キーボード上の '[{' キー
        OEM_5 = 0xDC,               // 標準キーボード上の '\|' キー
        OEM_6 = 0xDD,               // 標準キーボード上の ']}' キー
        OEM_7 = 0xDE,               // 標準キーボード上の ''"' キー
        OEM_8 = 0xDF,               // OEM 特殊キー
        OEM_102 = 0xE2,             // <> または \| キー (RT 102キーキーボード)
        ProcessKey = 0xE5,          // IME プロセスキー
        Packet = 0xE7,              // Packet キー
        Attn = 0xF6,                // Attnキー
        CrSel = 0xF7,               // CrSelキー
        ExSel = 0xF8,               // ExSelキー
        EraseEOF = 0xF9,            // Erase EOFキー
        Play = 0xFA,                // Playキー
        Zoom = 0xFB,                // Zoomキー
        PA1 = 0xFD,                 // PA1キー
        OEM_Clear = 0xFE            // OEM Clearキー
    };
}
